# ===================================
#  Relation Behavior Config
# ===================================

states:
    label: rainlab.location::lang.state.label
    list: ~/plugins/rainlab/location/models/state/columns.yaml
    form: ~/plugins/rainlab/location/models/state/fields.yaml
    view:
        showSearch: true
        toolbarPartial: $/rainlab/location/controllers/locations/_states_list_toolbar.htm
        filter: $/rainlab/location/models/state/filters.yaml
