<?php namespace RainLab\Location\Updates;

use October\Rain\Database\Updates\Seeder;
use RainLab\Location\Models\Country;

class SeedAllTables extends Seeder
{
    public function run()
    {
        Country::insert([
            ['is_enabled' => 1, 'code' => 'AU', 'iso_code' => 'AUS', 'calling_code' => 61, 'name' => 'Australia'],
            ['is_enabled' => 1, 'code' => 'CA', 'iso_code' => 'CAN', 'calling_code' => 1, 'name' => 'Canada'],
            ['is_enabled' => 1, 'code' => 'GB', 'iso_code' => 'GBR', 'calling_code' => 44, 'name' => 'United Kingdom'],
            ['is_enabled' => 1, 'code' => 'US', 'iso_code' => 'USA', 'calling_code' => 1, 'name' => 'United States'],

            ['is_enabled' => 0, 'code' => 'AF', 'iso_code' => 'AFG', 'calling_code' => 93, 'name' => 'Afghanistan'],
            ['is_enabled' => 0, 'code' => 'AX', 'iso_code' => 'ALA', 'calling_code' => 358, 'name' => 'Aland Islands '],
            ['is_enabled' => 0, 'code' => 'AL', 'iso_code' => 'ALB', 'calling_code' => 355, 'name' => 'Albania'],
            ['is_enabled' => 0, 'code' => 'DZ', 'iso_code' => 'DZA', 'calling_code' => 213, 'name' => 'Algeria'],
            ['is_enabled' => 0, 'code' => 'AS', 'iso_code' => 'ASM', 'calling_code' => 1684, 'name' => 'American Samoa'],
            ['is_enabled' => 0, 'code' => 'AD', 'iso_code' => 'AND', 'calling_code' => 376, 'name' => 'Andorra'],
            ['is_enabled' => 0, 'code' => 'AO', 'iso_code' => 'AGO', 'calling_code' => 244, 'name' => 'Angola'],
            ['is_enabled' => 0, 'code' => 'AI', 'iso_code' => 'AIA', 'calling_code' => 1264, 'name' => 'Anguilla'],
            ['is_enabled' => 0, 'code' => 'AQ', 'iso_code' => 'ATA', 'calling_code' => 672, 'name' => 'Antarctica'],
            ['is_enabled' => 0, 'code' => 'AG', 'iso_code' => 'ATG', 'calling_code' => 1268, 'name' => 'Antigua and Barbuda'],
            ['is_enabled' => 0, 'code' => 'AR', 'iso_code' => 'ARG', 'calling_code' => 54, 'name' => 'Argentina'],
            ['is_enabled' => 0, 'code' => 'AM', 'iso_code' => 'ARM', 'calling_code' => 374, 'name' => 'Armenia'],
            ['is_enabled' => 0, 'code' => 'AW', 'iso_code' => 'ABW', 'calling_code' => 297, 'name' => 'Aruba'],
            ['is_enabled' => 0, 'code' => 'AT', 'iso_code' => 'AUT', 'calling_code' => 43, 'name' => 'Austria'],
            ['is_enabled' => 0, 'code' => 'AZ', 'iso_code' => 'AZE', 'calling_code' => 994, 'name' => 'Azerbaijan'],
            ['is_enabled' => 0, 'code' => 'BS', 'iso_code' => 'BHS', 'calling_code' => 1242, 'name' => 'Bahamas'],
            ['is_enabled' => 0, 'code' => 'BH', 'iso_code' => 'BHR', 'calling_code' => 973, 'name' => 'Bahrain'],
            ['is_enabled' => 0, 'code' => 'BD', 'iso_code' => 'BGD', 'calling_code' => 880, 'name' => 'Bangladesh'],
            ['is_enabled' => 0, 'code' => 'BB', 'iso_code' => 'BRB', 'calling_code' => 1246, 'name' => 'Barbados'],
            ['is_enabled' => 0, 'code' => 'BY', 'iso_code' => 'BLR', 'calling_code' => 375, 'name' => 'Belarus'],
            ['is_enabled' => 0, 'code' => 'BE', 'iso_code' => 'BEL', 'calling_code' => 32, 'name' => 'Belgium'],
            ['is_enabled' => 0, 'code' => 'BZ', 'iso_code' => 'BLZ', 'calling_code' => 501, 'name' => 'Belize'],
            ['is_enabled' => 0, 'code' => 'BJ', 'iso_code' => 'BEN', 'calling_code' => 229, 'name' => 'Benin'],
            ['is_enabled' => 0, 'code' => 'BM', 'iso_code' => 'BMU', 'calling_code' => 1441, 'name' => 'Bermuda'],
            ['is_enabled' => 0, 'code' => 'BT', 'iso_code' => 'BTN', 'calling_code' => 975, 'name' => 'Bhutan'],
            ['is_enabled' => 0, 'code' => 'BO', 'iso_code' => 'BOL', 'calling_code' => 591, 'name' => 'Bolivia, Plurinational State of'],
            ['is_enabled' => 0, 'code' => 'BQ', 'iso_code' => 'BES', 'calling_code' => 599, 'name' => 'Bonaire, Sint Eustatius and Saba'],
            ['is_enabled' => 0, 'code' => 'BA', 'iso_code' => 'BIH', 'calling_code' => 387, 'name' => 'Bosnia and Herzegovina'],
            ['is_enabled' => 0, 'code' => 'BW', 'iso_code' => 'BWA', 'calling_code' => 267, 'name' => 'Botswana'],
            ['is_enabled' => 0, 'code' => 'BV', 'iso_code' => 'BVT', 'calling_code' => 55, 'name' => 'Bouvet Island'],
            ['is_enabled' => 0, 'code' => 'BR', 'iso_code' => 'BRA', 'calling_code' => 55, 'name' => 'Brazil'],
            ['is_enabled' => 0, 'code' => 'IO', 'iso_code' => 'IOT', 'calling_code' => 246, 'name' => 'British Indian Ocean Territory'],
            ['is_enabled' => 0, 'code' => 'BN', 'iso_code' => 'BRN', 'calling_code' => 673, 'name' => 'Brunei Darussalam'],
            ['is_enabled' => 0, 'code' => 'BG', 'iso_code' => 'BGR', 'calling_code' => 359, 'name' => 'Bulgaria'],
            ['is_enabled' => 0, 'code' => 'BF', 'iso_code' => 'BFA', 'calling_code' => 226, 'name' => 'Burkina Faso'],
            ['is_enabled' => 0, 'code' => 'BI', 'iso_code' => 'BDI', 'calling_code' => 257, 'name' => 'Burundi'],
            ['is_enabled' => 0, 'code' => 'KH', 'iso_code' => 'KHM', 'calling_code' => 855, 'name' => 'Cambodia'],
            ['is_enabled' => 0, 'code' => 'CM', 'iso_code' => 'CMR', 'calling_code' => 237, 'name' => 'Cameroon'],
            ['is_enabled' => 0, 'code' => 'CV', 'iso_code' => 'CPV', 'calling_code' => 238, 'name' => 'Cape Verde'],
            ['is_enabled' => 0, 'code' => 'KY', 'iso_code' => 'CYM', 'calling_code' => 1345, 'name' => 'Cayman Islands'],
            ['is_enabled' => 0, 'code' => 'CF', 'iso_code' => 'CAF', 'calling_code' => 236, 'name' => 'Central African Republic'],
            ['is_enabled' => 0, 'code' => 'TD', 'iso_code' => 'TCD', 'calling_code' => 235, 'name' => 'Chad'],
            ['is_enabled' => 0, 'code' => 'CL', 'iso_code' => 'CHL', 'calling_code' => 56, 'name' => 'Chile'],
            ['is_enabled' => 0, 'code' => 'CN', 'iso_code' => 'CHN', 'calling_code' => 86, 'name' => 'China'],
            ['is_enabled' => 0, 'code' => 'CX', 'iso_code' => 'CXR', 'calling_code' => 61, 'name' => 'Christmas Island'],
            ['is_enabled' => 0, 'code' => 'CC', 'iso_code' => 'CCK', 'calling_code' => 61, 'name' => 'Cocos (Keeling) Islands'],
            ['is_enabled' => 0, 'code' => 'CO', 'iso_code' => 'COL', 'calling_code' => 57, 'name' => 'Colombia'],
            ['is_enabled' => 0, 'code' => 'KM', 'iso_code' => 'COM', 'calling_code' => 269, 'name' => 'Comoros'],
            ['is_enabled' => 0, 'code' => 'CG', 'iso_code' => 'COG', 'calling_code' => 242, 'name' => 'Congo'],
            ['is_enabled' => 0, 'code' => 'CD', 'iso_code' => 'COD', 'calling_code' => 243, 'name' => 'Congo, the Democratic Republic of the'],
            ['is_enabled' => 0, 'code' => 'CK', 'iso_code' => 'COK', 'calling_code' => 682, 'name' => 'Cook Islands'],
            ['is_enabled' => 0, 'code' => 'CR', 'iso_code' => 'CRI', 'calling_code' => 506, 'name' => 'Costa Rica'],
            ['is_enabled' => 0, 'code' => 'CI', 'iso_code' => 'CIV', 'calling_code' => 225, 'name' => 'Cote d\'Ivoire'],
            ['is_enabled' => 0, 'code' => 'HR', 'iso_code' => 'HRV', 'calling_code' => 385, 'name' => 'Croatia'],
            ['is_enabled' => 0, 'code' => 'CU', 'iso_code' => 'CUB', 'calling_code' => 53, 'name' => 'Cuba'],
            ['is_enabled' => 0, 'code' => 'CW', 'iso_code' => 'CUW', 'calling_code' => 599, 'name' => 'Curaçao'],
            ['is_enabled' => 0, 'code' => 'CY', 'iso_code' => 'CYP', 'calling_code' => 357, 'name' => 'Cyprus'],
            ['is_enabled' => 0, 'code' => 'CZ', 'iso_code' => 'CZE', 'calling_code' => 420, 'name' => 'Czech Republic'],
            ['is_enabled' => 0, 'code' => 'DK', 'iso_code' => 'DNK', 'calling_code' => 45, 'name' => 'Denmark'],
            ['is_enabled' => 0, 'code' => 'DJ', 'iso_code' => 'DJI', 'calling_code' => 253, 'name' => 'Djibouti'],
            ['is_enabled' => 0, 'code' => 'DM', 'iso_code' => 'DMA', 'calling_code' => 1767, 'name' => 'Dominica'],
            ['is_enabled' => 0, 'code' => 'DO', 'iso_code' => 'DOM', 'calling_code' => 1809, 'name' => 'Dominican Republic'],
            ['is_enabled' => 0, 'code' => 'EC', 'iso_code' => 'ECU', 'calling_code' => 593, 'name' => 'Ecuador'],
            ['is_enabled' => 0, 'code' => 'EG', 'iso_code' => 'EGY', 'calling_code' => 20, 'name' => 'Egypt'],
            ['is_enabled' => 0, 'code' => 'SV', 'iso_code' => 'SLV', 'calling_code' => 503, 'name' => 'El Salvador'],
            ['is_enabled' => 0, 'code' => 'GQ', 'iso_code' => 'GNQ', 'calling_code' => 240, 'name' => 'Equatorial Guinea'],
            ['is_enabled' => 0, 'code' => 'ER', 'iso_code' => 'ERI', 'calling_code' => 291, 'name' => 'Eritrea'],
            ['is_enabled' => 0, 'code' => 'EE', 'iso_code' => 'EST', 'calling_code' => 372, 'name' => 'Estonia'],
            ['is_enabled' => 0, 'code' => 'ET', 'iso_code' => 'ETH', 'calling_code' => 251, 'name' => 'Ethiopia'],
            ['is_enabled' => 0, 'code' => 'FK', 'iso_code' => 'FLK', 'calling_code' => 500, 'name' => 'Falkland Islands (Malvinas)'],
            ['is_enabled' => 0, 'code' => 'FO', 'iso_code' => 'FRO', 'calling_code' => 298, 'name' => 'Faroe Islands'],
            ['is_enabled' => 0, 'code' => 'FI', 'iso_code' => 'FIN', 'calling_code' => 358, 'name' => 'Finland'],
            ['is_enabled' => 0, 'code' => 'FJ', 'iso_code' => 'FJI', 'calling_code' => 679, 'name' => 'Fiji'],
            ['is_enabled' => 1, 'code' => 'FR', 'iso_code' => 'FRA', 'calling_code' => 33, 'name' => 'France'],
            ['is_enabled' => 0, 'code' => 'GF', 'iso_code' => 'GUF', 'calling_code' => 594, 'name' => 'French Guiana'],
            ['is_enabled' => 0, 'code' => 'PF', 'iso_code' => 'PYF', 'calling_code' => 689, 'name' => 'French Polynesia'],
            ['is_enabled' => 0, 'code' => 'TF', 'iso_code' => 'ATF', 'calling_code' => 262, 'name' => 'French Southern Territories'],
            ['is_enabled' => 0, 'code' => 'GA', 'iso_code' => 'GAB', 'calling_code' => 241, 'name' => 'Gabon'],
            ['is_enabled' => 0, 'code' => 'GM', 'iso_code' => 'GMB', 'calling_code' => 220, 'name' => 'Gambia'],
            ['is_enabled' => 0, 'code' => 'GE', 'iso_code' => 'GEO', 'calling_code' => 995, 'name' => 'Georgia'],
            ['is_enabled' => 0, 'code' => 'DE', 'iso_code' => 'DEU', 'calling_code' => 49, 'name' => 'Germany'],
            ['is_enabled' => 0, 'code' => 'GH', 'iso_code' => 'GHA', 'calling_code' => 233, 'name' => 'Ghana'],
            ['is_enabled' => 0, 'code' => 'GI', 'iso_code' => 'GIB', 'calling_code' => 350, 'name' => 'Gibraltar'],
            ['is_enabled' => 0, 'code' => 'GR', 'iso_code' => 'GRC', 'calling_code' => 30, 'name' => 'Greece'],
            ['is_enabled' => 0, 'code' => 'GL', 'iso_code' => 'GRL', 'calling_code' => 299, 'name' => 'Greenland'],
            ['is_enabled' => 0, 'code' => 'GD', 'iso_code' => 'GRD', 'calling_code' => 1473, 'name' => 'Grenada'],
            ['is_enabled' => 0, 'code' => 'GP', 'iso_code' => 'GLP', 'calling_code' => 590, 'name' => 'Guadeloupe'],
            ['is_enabled' => 0, 'code' => 'GU', 'iso_code' => 'GUM', 'calling_code' => 1671, 'name' => 'Guam'],
            ['is_enabled' => 0, 'code' => 'GT', 'iso_code' => 'GTM', 'calling_code' => 502, 'name' => 'Guatemala'],
            ['is_enabled' => 0, 'code' => 'GG', 'iso_code' => 'GGY', 'calling_code' => 44, 'name' => 'Guernsey'],
            ['is_enabled' => 0, 'code' => 'GN', 'iso_code' => 'GIN', 'calling_code' => 224, 'name' => 'Guinea'],
            ['is_enabled' => 0, 'code' => 'GW', 'iso_code' => 'GNB', 'calling_code' => 245, 'name' => 'Guinea-Bissau'],
            ['is_enabled' => 0, 'code' => 'GY', 'iso_code' => 'GUY', 'calling_code' => 592, 'name' => 'Guyana'],
            ['is_enabled' => 0, 'code' => 'HT', 'iso_code' => 'HTI', 'calling_code' => 509, 'name' => 'Haiti'],
            ['is_enabled' => 0, 'code' => 'HM', 'iso_code' => 'HMD', 'calling_code' => 672, 'name' => 'Heard Island and McDonald Islands'],
            ['is_enabled' => 0, 'code' => 'VA', 'iso_code' => 'VAT', 'calling_code' => 39, 'name' => 'Holy See (Vatican City State)'],
            ['is_enabled' => 0, 'code' => 'HN', 'iso_code' => 'HND', 'calling_code' => 504, 'name' => 'Honduras'],
            ['is_enabled' => 0, 'code' => 'HK', 'iso_code' => 'HKG', 'calling_code' => 852, 'name' => 'Hong Kong'],
            ['is_enabled' => 1, 'code' => 'HU', 'iso_code' => 'HUN', 'calling_code' => 36, 'name' => 'Hungary'],
            ['is_enabled' => 0, 'code' => 'IS', 'iso_code' => 'ISL', 'calling_code' => 354, 'name' => 'Iceland'],
            ['is_enabled' => 1, 'code' => 'IN', 'iso_code' => 'IND', 'calling_code' => 91, 'name' => 'India'],
            ['is_enabled' => 0, 'code' => 'ID', 'iso_code' => 'IDN', 'calling_code' => 62, 'name' => 'Indonesia'],
            ['is_enabled' => 0, 'code' => 'IR', 'iso_code' => 'IRN', 'calling_code' => 98, 'name' => 'Iran, Islamic Republic of'],
            ['is_enabled' => 0, 'code' => 'IQ', 'iso_code' => 'IRQ', 'calling_code' => 964, 'name' => 'Iraq'],
            ['is_enabled' => 1, 'code' => 'IE', 'iso_code' => 'IRL', 'calling_code' => 353, 'name' => 'Ireland'],
            ['is_enabled' => 0, 'code' => 'IM', 'iso_code' => 'IMN', 'calling_code' => 44, 'name' => 'Isle of Man'],
            ['is_enabled' => 0, 'code' => 'IL', 'iso_code' => 'ISR', 'calling_code' => 972, 'name' => 'Israel'],
            ['is_enabled' => 0, 'code' => 'IT', 'iso_code' => 'ITA', 'calling_code' => 39, 'name' => 'Italy'],
            ['is_enabled' => 0, 'code' => 'JM', 'iso_code' => 'JAM', 'calling_code' => 1876, 'name' => 'Jamaica'],
            ['is_enabled' => 0, 'code' => 'JP', 'iso_code' => 'JPN', 'calling_code' => 81, 'name' => 'Japan'],
            ['is_enabled' => 0, 'code' => 'JE', 'iso_code' => 'JEY', 'calling_code' => 44, 'name' => 'Jersey'],
            ['is_enabled' => 0, 'code' => 'JO', 'iso_code' => 'JOR', 'calling_code' => 962, 'name' => 'Jordan'],
            ['is_enabled' => 0, 'code' => 'KZ', 'iso_code' => 'KAZ', 'calling_code' => 7, 'name' => 'Kazakhstan'],
            ['is_enabled' => 0, 'code' => 'KE', 'iso_code' => 'KEN', 'calling_code' => 254, 'name' => 'Kenya'],
            ['is_enabled' => 0, 'code' => 'KI', 'iso_code' => 'KIR', 'calling_code' => 686, 'name' => 'Kiribati'],
            ['is_enabled' => 0, 'code' => 'KP', 'iso_code' => 'PRK', 'calling_code' => 850, 'name' => 'Korea, Democratic People\'s Republic of'],
            ['is_enabled' => 0, 'code' => 'KR', 'iso_code' => 'KOR', 'calling_code' => 82, 'name' => 'Korea, Republic of'],
            ['is_enabled' => 0, 'code' => 'KW', 'iso_code' => 'KWT', 'calling_code' => 965, 'name' => 'Kuwait'],
            ['is_enabled' => 0, 'code' => 'KG', 'iso_code' => 'KGZ', 'calling_code' => 996, 'name' => 'Kyrgyzstan'],
            ['is_enabled' => 0, 'code' => 'LA', 'iso_code' => 'LAO', 'calling_code' => 856, 'name' => 'Lao People\'s Democratic Republic'],
            ['is_enabled' => 0, 'code' => 'LV', 'iso_code' => 'LVA', 'calling_code' => 371, 'name' => 'Latvia'],
            ['is_enabled' => 0, 'code' => 'LB', 'iso_code' => 'LBN', 'calling_code' => 961, 'name' => 'Lebanon'],
            ['is_enabled' => 0, 'code' => 'LS', 'iso_code' => 'LSO', 'calling_code' => 266, 'name' => 'Lesotho'],
            ['is_enabled' => 0, 'code' => 'LR', 'iso_code' => 'LBR', 'calling_code' => 231, 'name' => 'Liberia'],
            ['is_enabled' => 0, 'code' => 'LY', 'iso_code' => 'LBY', 'calling_code' => 218, 'name' => 'Libyan Arab Jamahiriya'],
            ['is_enabled' => 0, 'code' => 'LI', 'iso_code' => 'LIE', 'calling_code' => 423, 'name' => 'Liechtenstein'],
            ['is_enabled' => 0, 'code' => 'LT', 'iso_code' => 'LTU', 'calling_code' => 370, 'name' => 'Lithuania'],
            ['is_enabled' => 0, 'code' => 'LU', 'iso_code' => 'LUX', 'calling_code' => 352, 'name' => 'Luxembourg'],
            ['is_enabled' => 0, 'code' => 'MO', 'iso_code' => 'MAC', 'calling_code' => 853, 'name' => 'Macao'],
            ['is_enabled' => 0, 'code' => 'MK', 'iso_code' => 'MKD', 'calling_code' => 389, 'name' => 'North Macedonia'],
            ['is_enabled' => 0, 'code' => 'MG', 'iso_code' => 'MDG', 'calling_code' => 261, 'name' => 'Madagascar'],
            ['is_enabled' => 0, 'code' => 'MW', 'iso_code' => 'MWI', 'calling_code' => 265, 'name' => 'Malawi'],
            ['is_enabled' => 0, 'code' => 'MY', 'iso_code' => 'MYS', 'calling_code' => 60, 'name' => 'Malaysia'],
            ['is_enabled' => 0, 'code' => 'MV', 'iso_code' => 'MDV', 'calling_code' => 960, 'name' => 'Maldives'],
            ['is_enabled' => 0, 'code' => 'ML', 'iso_code' => 'MLI', 'calling_code' => 223, 'name' => 'Mali'],
            ['is_enabled' => 0, 'code' => 'MT', 'iso_code' => 'MLT', 'calling_code' => 356, 'name' => 'Malta'],
            ['is_enabled' => 0, 'code' => 'MH', 'iso_code' => 'MHL', 'calling_code' => 692, 'name' => 'Marshall Islands'],
            ['is_enabled' => 0, 'code' => 'MQ', 'iso_code' => 'MTQ', 'calling_code' => 596, 'name' => 'Martinique'],
            ['is_enabled' => 0, 'code' => 'MR', 'iso_code' => 'MRT', 'calling_code' => 222, 'name' => 'Mauritania'],
            ['is_enabled' => 0, 'code' => 'MU', 'iso_code' => 'MUS', 'calling_code' => 230, 'name' => 'Mauritius'],
            ['is_enabled' => 0, 'code' => 'YT', 'iso_code' => 'MYT', 'calling_code' => 262, 'name' => 'Mayotte'],
            ['is_enabled' => 0, 'code' => 'MX', 'iso_code' => 'MEX', 'calling_code' => 52, 'name' => 'Mexico'],
            ['is_enabled' => 0, 'code' => 'FM', 'iso_code' => 'FSM', 'calling_code' => 691, 'name' => 'Micronesia, Federated States of'],
            ['is_enabled' => 0, 'code' => 'MD', 'iso_code' => 'MDA', 'calling_code' => 373, 'name' => 'Moldova, Republic of'],
            ['is_enabled' => 0, 'code' => 'MC', 'iso_code' => 'MCO', 'calling_code' => 377, 'name' => 'Monaco'],
            ['is_enabled' => 0, 'code' => 'MN', 'iso_code' => 'MNG', 'calling_code' => 976, 'name' => 'Mongolia'],
            ['is_enabled' => 0, 'code' => 'ME', 'iso_code' => 'MNE', 'calling_code' => 382, 'name' => 'Montenegro'],
            ['is_enabled' => 0, 'code' => 'MS', 'iso_code' => 'MSR', 'calling_code' => 1664, 'name' => 'Montserrat'],
            ['is_enabled' => 0, 'code' => 'MA', 'iso_code' => 'MAR', 'calling_code' => 212, 'name' => 'Morocco'],
            ['is_enabled' => 0, 'code' => 'MZ', 'iso_code' => 'MOZ', 'calling_code' => 258, 'name' => 'Mozambique'],
            ['is_enabled' => 0, 'code' => 'MM', 'iso_code' => 'MMR', 'calling_code' => 95, 'name' => 'Myanmar'],
            ['is_enabled' => 0, 'code' => 'NA', 'iso_code' => 'NAM', 'calling_code' => 264, 'name' => 'Namibia'],
            ['is_enabled' => 0, 'code' => 'NR', 'iso_code' => 'NRU', 'calling_code' => 674, 'name' => 'Nauru'],
            ['is_enabled' => 0, 'code' => 'NP', 'iso_code' => 'NPL', 'calling_code' => 977, 'name' => 'Nepal'],
            ['is_enabled' => 1, 'code' => 'NL', 'iso_code' => 'NLD', 'calling_code' => 31, 'name' => 'Netherlands'],
            ['is_enabled' => 0, 'code' => 'NC', 'iso_code' => 'NCL', 'calling_code' => 687, 'name' => 'New Caledonia'],
            ['is_enabled' => 1, 'code' => 'NZ', 'iso_code' => 'NZL', 'calling_code' => 64, 'name' => 'New Zealand'],
            ['is_enabled' => 0, 'code' => 'NI', 'iso_code' => 'NIC', 'calling_code' => 505, 'name' => 'Nicaragua'],
            ['is_enabled' => 0, 'code' => 'NE', 'iso_code' => 'NER', 'calling_code' => 227, 'name' => 'Niger'],
            ['is_enabled' => 0, 'code' => 'NG', 'iso_code' => 'NGA', 'calling_code' => 234, 'name' => 'Nigeria'],
            ['is_enabled' => 0, 'code' => 'NU', 'iso_code' => 'NIU', 'calling_code' => 683, 'name' => 'Niue'],
            ['is_enabled' => 0, 'code' => 'NF', 'iso_code' => 'NFK', 'calling_code' => 672, 'name' => 'Norfolk Island'],
            ['is_enabled' => 0, 'code' => 'MP', 'iso_code' => 'MNP', 'calling_code' => 1670, 'name' => 'Northern Mariana Islands'],
            ['is_enabled' => 0, 'code' => 'NO', 'iso_code' => 'NOR', 'calling_code' => 47, 'name' => 'Norway'],
            ['is_enabled' => 0, 'code' => 'OM', 'iso_code' => 'OMN', 'calling_code' => 968, 'name' => 'Oman'],
            ['is_enabled' => 0, 'code' => 'PK', 'iso_code' => 'PAK', 'calling_code' => 92, 'name' => 'Pakistan'],
            ['is_enabled' => 0, 'code' => 'PW', 'iso_code' => 'PLW', 'calling_code' => 680, 'name' => 'Palau'],
            ['is_enabled' => 0, 'code' => 'PS', 'iso_code' => 'PSE', 'calling_code' => 970, 'name' => 'Palestine'],
            ['is_enabled' => 0, 'code' => 'PA', 'iso_code' => 'PAN', 'calling_code' => 507, 'name' => 'Panama'],
            ['is_enabled' => 0, 'code' => 'PG', 'iso_code' => 'PNG', 'calling_code' => 675, 'name' => 'Papua New Guinea'],
            ['is_enabled' => 0, 'code' => 'PY', 'iso_code' => 'PRY', 'calling_code' => 595, 'name' => 'Paraguay'],
            ['is_enabled' => 0, 'code' => 'PE', 'iso_code' => 'PER', 'calling_code' => 51, 'name' => 'Peru'],
            ['is_enabled' => 0, 'code' => 'PH', 'iso_code' => 'PHL', 'calling_code' => 63, 'name' => 'Philippines'],
            ['is_enabled' => 0, 'code' => 'PN', 'iso_code' => 'PCN', 'calling_code' => 870, 'name' => 'Pitcairn'],
            ['is_enabled' => 0, 'code' => 'PL', 'iso_code' => 'POL', 'calling_code' => 48, 'name' => 'Poland'],
            ['is_enabled' => 0, 'code' => 'PT', 'iso_code' => 'PRT', 'calling_code' => 351, 'name' => 'Portugal'],
            ['is_enabled' => 0, 'code' => 'PR', 'iso_code' => 'PRI', 'calling_code' => 1, 'name' => 'Puerto Rico'],
            ['is_enabled' => 0, 'code' => 'QA', 'iso_code' => 'QAT', 'calling_code' => 974, 'name' => 'Qatar'],
            ['is_enabled' => 0, 'code' => 'RE', 'iso_code' => 'REU', 'calling_code' => 262, 'name' => 'Reunion'],
            ['is_enabled' => 1, 'code' => 'RO', 'iso_code' => 'ROU', 'calling_code' => 40, 'name' => 'Romania'],
            ['is_enabled' => 0, 'code' => 'RU', 'iso_code' => 'RUS', 'calling_code' => 7, 'name' => 'Russian Federation'],
            ['is_enabled' => 0, 'code' => 'RW', 'iso_code' => 'RWA', 'calling_code' => 250, 'name' => 'Rwanda'],
            ['is_enabled' => 0, 'code' => 'BL', 'iso_code' => 'BLM', 'calling_code' => 590, 'name' => 'Saint Barthélemy'],
            ['is_enabled' => 0, 'code' => 'SH', 'iso_code' => 'SHN', 'calling_code' => 290, 'name' => 'Saint Helena'],
            ['is_enabled' => 0, 'code' => 'KN', 'iso_code' => 'KNA', 'calling_code' => 1869, 'name' => 'Saint Kitts and Nevis'],
            ['is_enabled' => 0, 'code' => 'LC', 'iso_code' => 'LCA', 'calling_code' => 1758, 'name' => 'Saint Lucia'],
            ['is_enabled' => 0, 'code' => 'MF', 'iso_code' => 'MAF', 'calling_code' => 1599, 'name' => 'Saint Martin (French part)'],
            ['is_enabled' => 0, 'code' => 'PM', 'iso_code' => 'SPM', 'calling_code' => 508, 'name' => 'Saint Pierre and Miquelon'],
            ['is_enabled' => 0, 'code' => 'VC', 'iso_code' => 'VCT', 'calling_code' => 1784, 'name' => 'Saint Vincent and the Grenadines'],
            ['is_enabled' => 0, 'code' => 'WS', 'iso_code' => 'WSM', 'calling_code' => 685, 'name' => 'Samoa'],
            ['is_enabled' => 0, 'code' => 'SM', 'iso_code' => 'SMR', 'calling_code' => 378, 'name' => 'San Marino'],
            ['is_enabled' => 0, 'code' => 'ST', 'iso_code' => 'STP', 'calling_code' => 239, 'name' => 'Sao Tome and Principe'],
            ['is_enabled' => 0, 'code' => 'SA', 'iso_code' => 'SAU', 'calling_code' => 966, 'name' => 'Saudi Arabia'],
            ['is_enabled' => 0, 'code' => 'SN', 'iso_code' => 'SEN', 'calling_code' => 221, 'name' => 'Senegal'],
            ['is_enabled' => 0, 'code' => 'RS', 'iso_code' => 'SRB', 'calling_code' => 381, 'name' => 'Serbia'],
            ['is_enabled' => 0, 'code' => 'SC', 'iso_code' => 'SYC', 'calling_code' => 248, 'name' => 'Seychelles'],
            ['is_enabled' => 0, 'code' => 'SL', 'iso_code' => 'SLE', 'calling_code' => 232, 'name' => 'Sierra Leone'],
            ['is_enabled' => 0, 'code' => 'SG', 'iso_code' => 'SGP', 'calling_code' => 65, 'name' => 'Singapore'],
            ['is_enabled' => 0, 'code' => 'SX', 'iso_code' => 'SXM', 'calling_code' => 599, 'name' => 'Sint Maarten (Dutch part)'],
            ['is_enabled' => 0, 'code' => 'SK', 'iso_code' => 'SVK', 'calling_code' => 421, 'name' => 'Slovakia'],
            ['is_enabled' => 0, 'code' => 'SI', 'iso_code' => 'SVN', 'calling_code' => 386, 'name' => 'Slovenia'],
            ['is_enabled' => 0, 'code' => 'SB', 'iso_code' => 'SLB', 'calling_code' => 677, 'name' => 'Solomon Islands'],
            ['is_enabled' => 0, 'code' => 'SO', 'iso_code' => 'SOM', 'calling_code' => 252, 'name' => 'Somalia'],
            ['is_enabled' => 0, 'code' => 'ZA', 'iso_code' => 'ZAF', 'calling_code' => 27, 'name' => 'South Africa'],
            ['is_enabled' => 0, 'code' => 'GS', 'iso_code' => 'SGS', 'calling_code' => 500, 'name' => 'South Georgia and the South Sandwich Islands'],
            ['is_enabled' => 1, 'code' => 'ES', 'iso_code' => 'ESP', 'calling_code' => 34, 'name' => 'Spain'],
            ['is_enabled' => 0, 'code' => 'LK', 'iso_code' => 'LKA', 'calling_code' => 94, 'name' => 'Sri Lanka'],
            ['is_enabled' => 0, 'code' => 'SD', 'iso_code' => 'SDN', 'calling_code' => 249, 'name' => 'Sudan'],
            ['is_enabled' => 0, 'code' => 'SR', 'iso_code' => 'SUR', 'calling_code' => 597, 'name' => 'Suriname'],
            ['is_enabled' => 0, 'code' => 'SJ', 'iso_code' => 'SJM', 'calling_code' => 47, 'name' => 'Svalbard and Jan Mayen'],
            ['is_enabled' => 0, 'code' => 'SZ', 'iso_code' => 'SWZ', 'calling_code' => 268, 'name' => 'Swaziland'],
            ['is_enabled' => 0, 'code' => 'SE', 'iso_code' => 'SWE', 'calling_code' => 46, 'name' => 'Sweden'],
            ['is_enabled' => 0, 'code' => 'CH', 'iso_code' => 'CHE', 'calling_code' => 41, 'name' => 'Switzerland'],
            ['is_enabled' => 0, 'code' => 'SY', 'iso_code' => 'SYR', 'calling_code' => 963, 'name' => 'Syrian Arab Republic'],
            ['is_enabled' => 0, 'code' => 'TW', 'iso_code' => 'TWN', 'calling_code' => 886, 'name' => 'Taiwan, Province of China'],
            ['is_enabled' => 0, 'code' => 'TJ', 'iso_code' => 'TJK', 'calling_code' => 992, 'name' => 'Tajikistan'],
            ['is_enabled' => 0, 'code' => 'TZ', 'iso_code' => 'TZA', 'calling_code' => 255, 'name' => 'Tanzania, United Republic of'],
            ['is_enabled' => 0, 'code' => 'TH', 'iso_code' => 'THA', 'calling_code' => 66, 'name' => 'Thailand'],
            ['is_enabled' => 0, 'code' => 'TL', 'iso_code' => 'TLS', 'calling_code' => 670, 'name' => 'Timor-Leste'],
            ['is_enabled' => 0, 'code' => 'TG', 'iso_code' => 'TGO', 'calling_code' => 228, 'name' => 'Togo'],
            ['is_enabled' => 0, 'code' => 'TK', 'iso_code' => 'TKL', 'calling_code' => 690, 'name' => 'Tokelau'],
            ['is_enabled' => 0, 'code' => 'TO', 'iso_code' => 'TON', 'calling_code' => 676, 'name' => 'Tonga'],
            ['is_enabled' => 0, 'code' => 'TT', 'iso_code' => 'TTO', 'calling_code' => 1868, 'name' => 'Trinidad and Tobago'],
            ['is_enabled' => 0, 'code' => 'TN', 'iso_code' => 'TUN', 'calling_code' => 216, 'name' => 'Tunisia'],
            ['is_enabled' => 0, 'code' => 'TR', 'iso_code' => 'TUR', 'calling_code' => 90, 'name' => 'Turkey'],
            ['is_enabled' => 0, 'code' => 'TM', 'iso_code' => 'TKM', 'calling_code' => 993, 'name' => 'Turkmenistan'],
            ['is_enabled' => 0, 'code' => 'TC', 'iso_code' => 'TCA', 'calling_code' => 1649, 'name' => 'Turks and Caicos Islands'],
            ['is_enabled' => 0, 'code' => 'TV', 'iso_code' => 'TUV', 'calling_code' => 688, 'name' => 'Tuvalu'],
            ['is_enabled' => 0, 'code' => 'UG', 'iso_code' => 'UGA', 'calling_code' => 256, 'name' => 'Uganda'],
            ['is_enabled' => 0, 'code' => 'UA', 'iso_code' => 'UKR', 'calling_code' => 380, 'name' => 'Ukraine'],
            ['is_enabled' => 0, 'code' => 'AE', 'iso_code' => 'ARE', 'calling_code' => 971, 'name' => 'United Arab Emirates'],
            ['is_enabled' => 0, 'code' => 'UM', 'iso_code' => 'UMI', 'calling_code' => 246, 'name' => 'United States Minor Outlying Islands'],
            ['is_enabled' => 0, 'code' => 'UY', 'iso_code' => 'URY', 'calling_code' => 598, 'name' => 'Uruguay'],
            ['is_enabled' => 0, 'code' => 'UZ', 'iso_code' => 'UZB', 'calling_code' => 998, 'name' => 'Uzbekistan'],
            ['is_enabled' => 0, 'code' => 'VU', 'iso_code' => 'VUT', 'calling_code' => 678, 'name' => 'Vanuatu'],
            ['is_enabled' => 0, 'code' => 'VE', 'iso_code' => 'VEN', 'calling_code' => 58, 'name' => 'Venezuela, Bolivarian Republic of'],
            ['is_enabled' => 0, 'code' => 'VN', 'iso_code' => 'VNM', 'calling_code' => 84, 'name' => 'Viet Nam'],
            ['is_enabled' => 0, 'code' => 'VG', 'iso_code' => 'VGB', 'calling_code' => 1284, 'name' => 'Virgin Islands, British'],
            ['is_enabled' => 0, 'code' => 'VI', 'iso_code' => 'VIR', 'calling_code' => 1340, 'name' => 'Virgin Islands, U.S.'],
            ['is_enabled' => 0, 'code' => 'WF', 'iso_code' => 'WLF', 'calling_code' => 681, 'name' => 'Wallis and Futuna'],
            ['is_enabled' => 0, 'code' => 'EH', 'iso_code' => 'ESH', 'calling_code' => 212, 'name' => 'Western Sahara'],
            ['is_enabled' => 0, 'code' => 'YE', 'iso_code' => 'YEM', 'calling_code' => 967, 'name' => 'Yemen'],
            ['is_enabled' => 0, 'code' => 'ZM', 'iso_code' => 'ZMB', 'calling_code' => 260, 'name' => 'Zambia'],
            ['is_enabled' => 0, 'code' => 'ZW', 'iso_code' => 'ZWE', 'calling_code' => 263, 'name' => 'Zimbabwe'],
        ]);
    }
}
